CREATE SCHEMA MULTIMEDIA_CORPUS;
CREATE TABLE MULTIMEDIA_CORPUS.MULTIMEDIA_TYPES
(
MULTIMEDIA_TYPE_ID SERIAL PRIMARY KEY,
MULTIMEDIA_TYPE VARCHAR(50) NOT NULL

);


CREATE TABLE MULTIMEDIA_CORPUS.MULTIMEDIA
(
MULTIMEDIA_ID SERIAL PRIMARY KEY,
MULTIMEDIA_TYPE_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.MULTIMEDIA_TYPES(MULTIMEDIA_TYPE_ID) NOT NULL,
MULTIMEDIA_URL TEXT NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.PLACES
(
PLACE_ID SERIAL PRIMARY KEY,
PLACE_NAME TEXT NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.LANGUAGES
(
LANGUAGE_ID SERIAL PRIMARY KEY,
LANGUAGE_NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE MULTIMEDIA_CORPUS.PARTS_OF_SPEECH
(
POS_ID SERIAL PRIMARY KEY,
POS_NAME TEXT NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.SPEAKERS
(
SPEAKER_ID SERIAL PRIMARY KEY, 
SURNAME TEXT NOT NULL,
PATRONYMIC TEXT,
NAME TEXT NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.EXPEDITIONS
(
EXPEDITION_ID SERIAL PRIMARY KEY, 
DATE_FROM DATE NOT NULL, 
DATE_TO DATE NOT NULL, 
DESCRIPTION VARCHAR(1000)
);

CREATE TABLE MULTIMEDIA_CORPUS.TEXTS
(
TEXT_ID SERIAL PRIMARY KEY,
ORIGINAL_NAME TEXT NOT NULL,
TRANSLATION_NAME TEXT NOT NULL,
SITE_URL TEXT,
SPEAKER_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.SPEAKERS(SPEAKER_ID) NOT NULL,
EXPEDITION_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.EXPEDITIONS(EXPEDITION_ID) NOT NULL,
PLACE_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.PLACES(PLACE_ID) NOT NULL,
LANGUAGE_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.LANGUAGES(LANGUAGE_ID) NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.TEXTS_MULTIMEDIA
(
TEXT_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.TEXTS(TEXT_ID) NOT NULL,
MULTIMEDIA_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.MULTIMEDIA(MULTIMEDIA_ID) NOT NULL UNIQUE,
IS_MAIN BOOLEAN NOT NULL
);


CREATE TABLE MULTIMEDIA_CORPUS.SENTENCES
(
SENTENCE_ID SERIAL PRIMARY KEY,
TEXT_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.TEXTS(TEXT_ID) NOT NULL,
MULTIMEDIA_START INTEGER NOT NULL,
MULTIMEDIA_END INTEGER NOT NULL,
ORIGINAL_TEXT TEXT NOT NULL,
TRANSLATION_TEXT TEXT NOT NULL
);

CREATE TABLE MULTIMEDIA_CORPUS.WORDS
(
WORD_ID SERIAL PRIMARY KEY,
WORD_TRANSCRIPTION TEXT NOT NULL,
SENTENCE_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.SENTENCES(SENTENCE_ID) NOT NULL,
WORD_ORDER INTEGER NOT NULL,
POS_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.PARTS_OF_SPEECH(POS_ID)
);

CREATE TABLE MULTIMEDIA_CORPUS.MORPHEMES
(
MORPHEME_ID SERIAL PRIMARY KEY,
MORPHEME_TYPE VARCHAR(1) NOT NULL,
MORPHEME_TEXT TEXT NOT NULL,
MORPHEME_GLOSS TEXT NOT NULL,
WORD_ID INTEGER REFERENCES MULTIMEDIA_CORPUS.WORDS(WORD_ID) NOT NULL,
MORPHEME_ORDER INTEGER NOT NULL
);

